services:
  back:
    container_name: hibr-back
    build: ./back
    volumes:
      - db:/db
    networks:
      - app-network
    restart: unless-stopped

  front:
    container_name: hibr-front
    build: ./front
    networks:
      - app-network
    restart: unless-stopped

  rp:
    image: caddy
    container_name: hibr-rp
    environment:
      - BACK_HOST=hibr-back:8080
      - FRONT_HOST=hibr-front:80
      - PUBLIC_HOST=hibr.jody.page
    ports:
      - "8081:8081"
    volumes:
      - ./rp:/etc/caddy
      - rp:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db:
  rp:

networks:
  app-network:
    driver: bridge
